[package]
name = "touying-flow"
version = "1.0.0"
entrypoint = "theme.typ"
authors = ["Quaternijkon<https://github.com/Quaternijkon>"]
license = "MIT"
description = "Eliminate irrelevant decorative elements to better focus on the content itself."
repository = "https://github.com/Quaternijkon/Typst_FLOW"
keywords = ["presentation", "slides", "lecture", "touying"]
categories = ["presentation"]
disciplines = []
compiler = "0.11.0"
exclude = []

[template]
path = "content/example"
entrypoint = "main.typ"
thumbnail = "image.png"